version: '3.8'
services:
  expensetracker-api:
    build:
      context: expensetracker-api
      dockerfile: Dockerfile.layered
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://expensetracker-db:5432/expensedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "18080:8080"
    restart: always
    depends_on:
      - expensetracker-db
  expensetracker-gui:
    container_name: expensetracker-gui
    build:
      context: expensetracker-gui
      dockerfile: Dockerfile
    ports:
        - "10443:10443"
    environment:
      REACT_APP_API_URL: http://localhost:18080/api/expense/
    restart: always
    depends_on:
      - expensetracker-api