version: '3.8'
services:
  expensetracker-db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=expensedb
    ports:
      - "15432:5432"