server:
  port: 10443
spring:
  application:
    name: xpense-api-gateway
  cloud:
    gateway:
      default-filters:
         - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: xpense-service
          uri: http://localhost:18080/
          predicates:
            - Path=/xpense/service/**