INSERT INTO transaction
(amount,created_at,type,category,description,transaction_date) VALUES
(150000.00,CURRENT_TIMESTAMP,'INCOME','OTHER','Salary', CURRENT_TIMESTAMP),
(1000.00,CURRENT_TIMESTAMP,'EXPENSE','ENTERTAINMENT','Movies', CURRENT_TIMESTAMP),
(1200.00,CURRENT_TIMESTAMP,'EXPENSE','FOOD','Swiggy', CURRENT_TIMESTAMP),
(1100.00,CURRENT_TIMESTAMP,'EXPENSE','OTHER','Medical Bills', CURRENT_TIMESTAMP),
(400.00,CURRENT_TIMESTAMP,'EXPENSE','RENT','OLA', CURRENT_TIMESTAMP),
(1300.00,CURRENT_TIMESTAMP,'EXPENSE','FOOD','Swiggy', CURRENT_TIMESTAMP),
(500.00,CURRENT_TIMESTAMP,'EXPENSE','FOOD','Thoms', CURRENT_TIMESTAMP),
(800.00,CURRENT_TIMESTAMP,'EXPENSE','TRANSPORTATION','Fuel', CURRENT_TIMESTAMP),
(7000.00,CURRENT_TIMESTAMP,'EXPENSE','GROCERIES','Ration', CURRENT_TIMESTAMP),
(1300.00,CURRENT_TIMESTAMP,'EXPENSE','SHOPPING','Clothes', CURRENT_TIMESTAMP),
(14000.00,CURRENT_TIMESTAMP,'EXPENSE','LOAN','Personal Loan', CURRENT_TIMESTAMP),
(5600.00,CURRENT_TIMESTAMP,'INVESTMENT','STOCKS','Smallcase', CURRENT_TIMESTAMP),
(2100.00,CURRENT_TIMESTAMP,'EXPENSE','GROCERIES','Ration', CURRENT_TIMESTAMP),
(2500.00,CURRENT_TIMESTAMP,'INVESTMENT','STOCKS','IND money', CURRENT_TIMESTAMP),
(10000.00,CURRENT_TIMESTAMP,'INVESTMENT','MUTUAL_FUNDS','Scripbox', CURRENT_TIMESTAMP),
(10000.00,CURRENT_TIMESTAMP,'INVESTMENT','MUTUAL_FUNDS','Scripbox', CURRENT_TIMESTAMP);