name: Build expensetracker-api

on:
  push:
    branches: [ "**" ]

jobs:
  build-expensetracker-api:
    name: Build expensetracker-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./expensetracker-api
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw verify

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          ./mvnw clean package jib:dockerBuild -DskipTests
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/expensetracker-api
  build-expensetracker-gui:
    name: Build expensetracker-gui
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./expensetracker-gui
    strategy:
      matrix:
        node-version: [ 12.x, 14.x ,16.x ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/expensetracker-gui .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/expensetracker-gui
